# Generated by Django 2.2 on 2019-05-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='contanct_address',
            new_name='contact_address',
        ),
    ]
