# Generated by Django 2.2 on 2019-06-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20190605_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
